[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200

# Allow assets to load normally
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Prevent JS files from being redirected to index.html
[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200